// GENERATED by tools/gen_engine_assets.py from kynetica-marketing/engine/fix-library.csv. Do not edit.
export const FIX_LIBRARY = [
{
"id": "FL-001",
"trade": "all",
"stage": "call_to_job",
"leak_category": "double_entry",
"leak_pattern": "Job first written on paper in the truck then re-typed at night",
"signal_words": [
"paper ticket",
"carbon copy",
"notepad",
"re-type",
"QuickBooks at night",
"on paper",
"paper",
"whiteboard",
"re-key"
],
"automation_category": "single_entry_mobile_form",
"tools_owner_likely_has": [
"phone camera",
"shared spreadsheet",
"invoicing software import"
],
"manual_step_that_stays": "tech confirms job details with the customer on site",
"hours_week_low": 3.0,
"hours_week_high": 5.0,
"setup_hours_low": 1.0,
"setup_hours_high": 3.0,
"estimate_basis": "one ticket per job x jobs/day x minutes to re-type + correction rework; needs jobs/day from owner",
"anti_pattern_to_reject": "photograph the ticket and text it to the office (moves the re-typing, does not remove it)"
},
{
"id": "FL-002",
"trade": "all",
"stage": "call_to_job",
"leak_category": "capture_at_source",
"leak_pattern": "Owner answers the phone between jobs and writes nothing down until later",
"signal_words": [
"phone between jobs",
"forgot",
"call back",
"sticky note"
],
"automation_category": "call_capture_form",
"tools_owner_likely_has": [
"phone",
"call-forwarding",
"a form that texts the office",
"voicemail-to-text"
],
"manual_step_that_stays": "owner still decides the schedule",
"hours_week_low": 2.0,
"hours_week_high": 4.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "missed/duplicated jobs per month x hours to recover; needs calls/day",
"anti_pattern_to_reject": "tell the owner to keep a notebook in the truck"
},
{
"id": "FL-003",
"trade": "all",
"stage": "call_to_job",
"leak_category": "after_hours_response",
"leak_pattern": "After-hours quote request answered manually at 9pm from the phone",
"signal_words": [
"9pm",
"9 at night",
"after hours",
"text me a quote",
"late reply",
"quote",
"from bed",
"at night for"
],
"automation_category": "auto_reply_with_intake",
"tools_owner_likely_has": [
"business texting app",
"website form",
"canned response feature in phone"
],
"manual_step_that_stays": "owner still prices the job",
"hours_week_low": 2.0,
"hours_week_high": 3.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "quote requests/week x minutes each; needs requests/week",
"anti_pattern_to_reject": "copy-paste a saved reply each time (still manual, still at 9pm)"
},
{
"id": "FL-004",
"trade": "all",
"stage": "call_to_job",
"leak_category": "scheduling_mixup",
"leak_pattern": "Double-booked or missed appointments from a paper or head calendar",
"signal_words": [
"double booked",
"forgot the appointment",
"paper calendar",
"whiteboard"
],
"automation_category": "shared_calendar_with_confirmations",
"tools_owner_likely_has": [
"phone calendar",
"Google/Outlook calendar",
"scheduling software already paid for"
],
"manual_step_that_stays": "owner assigns crews",
"hours_week_low": 1.0,
"hours_week_high": 3.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "mix-ups/month x hours lost each (drive + re-schedule); needs mix-ups/month",
"anti_pattern_to_reject": "print the calendar each morning"
},
{
"id": "FL-005",
"trade": "all",
"stage": "call_to_job",
"leak_category": "no_show",
"leak_pattern": "Customer no-shows or not-home on arrival",
"signal_words": [
"nobody home",
"no-show",
"drove out for nothing"
],
"automation_category": "appointment_reminder_sms",
"tools_owner_likely_has": [
"scheduling software reminder feature",
"texting app"
],
"manual_step_that_stays": "dispatcher handles reschedules",
"hours_week_low": 1.0,
"hours_week_high": 3.0,
"setup_hours_low": 0.5,
"setup_hours_high": 1.0,
"estimate_basis": "no-shows/month x (drive time + lost slot); needs no-show rate",
"anti_pattern_to_reject": "call every customer the night before"
},
{
"id": "FL-006",
"trade": "all",
"stage": "call_to_job",
"leak_category": "double_entry",
"leak_pattern": "Same customer info typed into quote then invoice then calendar",
"signal_words": [
"type it three times",
"same info",
"copy over"
],
"automation_category": "record_once_sync",
"tools_owner_likely_has": [
"invoicing software customer list",
"connector between calendar and invoicing"
],
"manual_step_that_stays": "none once linked",
"hours_week_low": 2.0,
"hours_week_high": 4.0,
"setup_hours_low": 1.0,
"setup_hours_high": 3.0,
"estimate_basis": "customers/week x 3 entries x minutes; needs new customers/week",
"anti_pattern_to_reject": "a master spreadsheet the owner updates by hand"
},
{
"id": "FL-007",
"trade": "all",
"stage": "job_to_invoice",
"leak_category": "invoice_creation_delay",
"leak_pattern": "Invoice created at night from the day's job notes",
"signal_words": [
"invoice at night",
"kitchen table",
"after dinner",
"re-keys",
"dispatcher",
"at 5"
],
"automation_category": "invoice_from_completed_job",
"tools_owner_likely_has": [
"invoicing software mobile app",
"job-complete trigger"
],
"manual_step_that_stays": "tech marks job done and confirms parts",
"hours_week_low": 3.0,
"hours_week_high": 5.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "jobs/day x minutes per invoice; needs jobs/day",
"anti_pattern_to_reject": "have the spouse do it instead of the owner"
},
{
"id": "FL-008",
"trade": "all",
"stage": "job_to_invoice",
"leak_category": "parts_capture",
"leak_pattern": "Part numbers wrong on invoice because captured from memory or handwriting",
"signal_words": [
"wrong part",
"redo the invoice",
"part number"
],
"automation_category": "capture_parts_at_site",
"tools_owner_likely_has": [
"phone camera on the part label",
"parts list in invoicing app"
],
"manual_step_that_stays": "tech picks the part",
"hours_week_low": 1.0,
"hours_week_high": 3.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "corrections/week x minutes to redo + customer call; needs corrections/week",
"anti_pattern_to_reject": "tell techs to write more clearly"
},
{
"id": "FL-009",
"trade": "all",
"stage": "job_to_invoice",
"leak_category": "quote_follow_up",
"leak_pattern": "Quotes sit in a notebook and are never followed up",
"signal_words": [
"forgot to follow up",
"quote went cold",
"never heard back"
],
"automation_category": "quote_follow_up_sequence",
"tools_owner_likely_has": [
"invoicing/quoting software reminder",
"email or SMS scheduled send"
],
"manual_step_that_stays": "owner writes the quote",
"hours_week_low": 1.0,
"hours_week_high": 2.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "open quotes/month x follow-ups x minutes; needs quotes/month",
"anti_pattern_to_reject": "a weekly reminder to the owner to go through the notebook"
},
{
"id": "FL-010",
"trade": "all",
"stage": "job_to_invoice",
"leak_category": "photo_handoff",
"leak_pattern": "Photos of the job live on the tech's phone and never reach the invoice or customer",
"signal_words": [
"photos on his phone",
"send me the pictures",
"before and after"
],
"automation_category": "photo_to_job_record",
"tools_owner_likely_has": [
"shared album",
"job field in scheduling app",
"cloud folder auto-upload"
],
"manual_step_that_stays": "tech takes the photos",
"hours_week_low": 1.0,
"hours_week_high": 2.0,
"setup_hours_low": 0.5,
"setup_hours_high": 1.0,
"estimate_basis": "jobs needing photos/week x minutes chasing; needs jobs/week",
"anti_pattern_to_reject": "text the photos to the owner each night"
},
{
"id": "FL-011",
"trade": "all",
"stage": "job_to_invoice",
"leak_category": "change_order",
"leak_pattern": "Change orders agreed verbally on site and forgotten at billing",
"signal_words": [
"forgot to bill",
"extra work",
"he said it was fine"
],
"automation_category": "change_order_capture_form",
"tools_owner_likely_has": [
"phone form",
"quoting app add-line",
"customer text approval"
],
"manual_step_that_stays": "customer approves",
"hours_week_low": 1.0,
"hours_week_high": 2.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "unbilled extras/month x average $; hours are the owner's recon time; needs extras/month",
"anti_pattern_to_reject": "remind techs to mention extras"
},
{
"id": "FL-012",
"trade": "all",
"stage": "invoice_to_money",
"leak_category": "payment_chasing",
"leak_pattern": "Owner chases unpaid invoices by phone on Fridays",
"signal_words": [
"chasing invoices",
"Friday calls",
"pay when they feel like it"
],
"automation_category": "payment_reminder_sequence",
"tools_owner_likely_has": [
"invoicing software reminders",
"pay link",
"card on file"
],
"manual_step_that_stays": "owner calls only the day-21 list",
"hours_week_low": 2.0,
"hours_week_high": 3.0,
"setup_hours_low": 0.5,
"setup_hours_high": 1.0,
"estimate_basis": "open invoices x reminder calls x minutes; needs open invoices/month",
"anti_pattern_to_reject": "block out Friday afternoon for collections"
},
{
"id": "FL-013",
"trade": "all",
"stage": "invoice_to_money",
"leak_category": "payment_collection_method",
"leak_pattern": "Checks collected on site and driven to the bank",
"signal_words": [
"check",
"drive to the bank",
"deposit"
],
"automation_category": "card_or_ach_on_site",
"tools_owner_likely_has": [
"invoicing app payment link",
"mobile card reader",
"bank mobile deposit"
],
"manual_step_that_stays": "none",
"hours_week_low": 1.0,
"hours_week_high": 2.0,
"setup_hours_low": 0.5,
"setup_hours_high": 1.0,
"estimate_basis": "deposits/week x drive time; needs deposits/week",
"anti_pattern_to_reject": "batch the bank run to once a week"
},
{
"id": "FL-014",
"trade": "all",
"stage": "invoice_to_money",
"leak_category": "deposit_tracking",
"leak_pattern": "Deposits for big jobs requested by phone and tracked in the owner's head",
"signal_words": [
"deposit",
"half up front",
"did they pay the deposit"
],
"automation_category": "deposit_request_with_link",
"tools_owner_likely_has": [
"quoting software deposit feature",
"payment link"
],
"manual_step_that_stays": "owner sets deposit amount",
"hours_week_low": 1.0,
"hours_week_high": 2.0,
"setup_hours_low": 0.5,
"setup_hours_high": 1.0,
"estimate_basis": "large jobs/month x minutes tracking; needs large jobs/month",
"anti_pattern_to_reject": "a sticky note on the quote"
},
{
"id": "FL-015",
"trade": "all",
"stage": "invoice_to_money",
"leak_category": "reconciliation",
"leak_pattern": "Payments received but not matched to invoices in the books",
"signal_words": [
"who paid",
"reconcile",
"which invoice"
],
"automation_category": "payment_to_invoice_matching",
"tools_owner_likely_has": [
"invoicing software bank feed",
"payment processor sync"
],
"manual_step_that_stays": "bookkeeper reviews exceptions",
"hours_week_low": 1.0,
"hours_week_high": 3.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "payments/month x minutes matching; needs payments/month",
"anti_pattern_to_reject": "print the bank statement and tick it off"
},
{
"id": "FL-016",
"trade": "all",
"stage": "invoice_to_money",
"leak_category": "review_request",
"leak_pattern": "Review requests never sent or sent by hand to a few customers",
"signal_words": [
"reviews",
"Google reviews",
"ask for a review"
],
"automation_category": "post_job_review_request",
"tools_owner_likely_has": [
"scheduling software follow-up",
"SMS template on job close"
],
"manual_step_that_stays": "tech does a good job",
"hours_week_low": 0.5,
"hours_week_high": 1.0,
"setup_hours_low": 0.5,
"setup_hours_high": 1.0,
"estimate_basis": "jobs/week x minutes per manual ask; needs jobs/week",
"anti_pattern_to_reject": "ask in person and hope"
},
{
"id": "FL-017",
"trade": "HVAC",
"stage": "call_to_job",
"leak_category": "renewal_recurring",
"leak_pattern": "Maintenance-plan renewals tracked in a spreadsheet and called one by one",
"signal_words": [
"maintenance plan",
"renewal",
"tune-up season",
"call the list"
],
"automation_category": "renewal_reminder_sequence",
"tools_owner_likely_has": [
"customer list export",
"email/SMS scheduled sends",
"invoicing recurring billing"
],
"manual_step_that_stays": "owner sets plan price",
"hours_week_low": 2.0,
"hours_week_high": 4.0,
"setup_hours_low": 1.0,
"setup_hours_high": 3.0,
"estimate_basis": "plan members x contacts/year x minutes; needs plan count",
"anti_pattern_to_reject": "hire a seasonal caller"
},
{
"id": "FL-018",
"trade": "HVAC",
"stage": "job_to_invoice",
"leak_category": "paperwork_prefill",
"leak_pattern": "Manufacturer rebate paperwork filled out by hand per install",
"signal_words": [
"rebate",
"warranty registration",
"paperwork per install"
],
"automation_category": "rebate_form_prefill",
"tools_owner_likely_has": [
"install record fields",
"PDF form fill",
"shared drive"
],
"manual_step_that_stays": "owner signs",
"hours_week_low": 1.0,
"hours_week_high": 2.0,
"setup_hours_low": 1.0,
"setup_hours_high": 3.0,
"estimate_basis": "installs/month x minutes per form; needs installs/month",
"anti_pattern_to_reject": "let the customer file the rebate"
},
{
"id": "FL-019",
"trade": "HVAC",
"stage": "call_to_job",
"leak_category": "overflow_intake",
"leak_pattern": "Peak-season overflow calls go to voicemail and are lost",
"signal_words": [
"first hot week",
"voicemail full",
"couldn't keep up"
],
"automation_category": "overflow_intake_form_and_callback_list",
"tools_owner_likely_has": [
"call forwarding",
"web form",
"texting app"
],
"manual_step_that_stays": "dispatcher prioritises",
"hours_week_low": 2.0,
"hours_week_high": 4.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "missed calls/day in peak x conversion x job value; hours = call-back time; needs missed calls",
"anti_pattern_to_reject": "an answering service that takes messages on paper"
},
{
"id": "FL-020",
"trade": "HVAC",
"stage": "job_to_invoice",
"leak_category": "parts_capture",
"leak_pattern": "Equipment model and serial numbers copied from the unit by hand onto the ticket",
"signal_words": [
"serial number",
"model number",
"wrote it down wrong"
],
"automation_category": "photo_capture_of_data_plate",
"tools_owner_likely_has": [
"phone camera",
"job record attachment"
],
"manual_step_that_stays": "tech photographs the plate",
"hours_week_low": 0.5,
"hours_week_high": 1.0,
"setup_hours_low": 0.5,
"setup_hours_high": 1.0,
"estimate_basis": "installs+repairs/week x minutes + rework; needs jobs/week",
"anti_pattern_to_reject": "write bigger"
},
{
"id": "FL-021",
"trade": "Plumbing",
"stage": "call_to_job",
"leak_category": "after_hours_triage",
"leak_pattern": "Emergency calls at night triaged by the owner personally",
"signal_words": [
"burst pipe",
"3am",
"emergency line"
],
"automation_category": "after_hours_triage_form_and_rotation",
"tools_owner_likely_has": [
"call forwarding rules",
"on-call calendar",
"texting app"
],
"manual_step_that_stays": "on-call plumber decides to roll",
"hours_week_low": 1.0,
"hours_week_high": 3.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "after-hours calls/week x minutes triage; needs calls/week",
"anti_pattern_to_reject": "owner keeps the phone by the bed"
},
{
"id": "FL-022",
"trade": "Plumbing",
"stage": "job_to_invoice",
"leak_category": "parts_capture",
"leak_pattern": "Parts bought at the supply house on the way to the job and lost at billing",
"signal_words": [
"supply house",
"receipt in the truck",
"forgot to bill the parts",
"receipts",
"scan",
"scanning",
"invoices and receipts"
],
"automation_category": "receipt_photo_to_job",
"tools_owner_likely_has": [
"phone camera",
"expense capture in invoicing app",
"supply-house account export"
],
"manual_step_that_stays": "plumber buys the part",
"hours_week_low": 1.0,
"hours_week_high": 2.0,
"setup_hours_low": 0.5,
"setup_hours_high": 1.0,
"estimate_basis": "supply runs/week x minutes + unbilled parts; needs runs/week",
"anti_pattern_to_reject": "a shoebox for receipts"
},
{
"id": "FL-023",
"trade": "Plumbing",
"stage": "invoice_to_money",
"leak_category": "payment_chasing",
"leak_pattern": "Property-manager accounts invoiced by email one at a time and paid late",
"signal_words": [
"property manager",
"net 30",
"statement"
],
"automation_category": "batched_statements_and_portal",
"tools_owner_likely_has": [
"invoicing software statements",
"recurring invoices",
"pay link"
],
"manual_step_that_stays": "owner approves the batch",
"hours_week_low": 1.0,
"hours_week_high": 2.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "PM accounts x invoices/month x minutes; needs account count",
"anti_pattern_to_reject": "call the PM office every month"
},
{
"id": "FL-024",
"trade": "Electrical",
"stage": "call_to_job",
"leak_category": "permit_tracking",
"leak_pattern": "Permit and inspection scheduling tracked by memory and phone calls",
"signal_words": [
"permit",
"inspection",
"inspector",
"pull the permit"
],
"automation_category": "permit_tracking_checklist_with_reminders",
"tools_owner_likely_has": [
"shared calendar",
"job checklist field",
"municipality online portal"
],
"manual_step_that_stays": "electrician meets the inspector",
"hours_week_low": 1.0,
"hours_week_high": 2.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "permits/month x minutes tracking; needs permits/month",
"anti_pattern_to_reject": "a whiteboard of open permits"
},
{
"id": "FL-025",
"trade": "Electrical",
"stage": "job_to_invoice",
"leak_category": "materials_takeoff",
"leak_pattern": "Materials lists built per job by hand and re-typed into the quote",
"signal_words": [
"materials list",
"take-off",
"wire and boxes"
],
"automation_category": "materials_template_per_job_type",
"tools_owner_likely_has": [
"quote templates in quoting software",
"line-item library"
],
"manual_step_that_stays": "electrician adjusts quantities",
"hours_week_low": 1.0,
"hours_week_high": 3.0,
"setup_hours_low": 1.0,
"setup_hours_high": 3.0,
"estimate_basis": "quotes/week x minutes building list; needs quotes/week",
"anti_pattern_to_reject": "keep last quote and edit it"
},
{
"id": "FL-026",
"trade": "Roofing",
"stage": "call_to_job",
"leak_category": "lead_surge",
"leak_pattern": "Storm-season lead surge handled by owner texting each lead back",
"signal_words": [
"storm",
"hail",
"leads piling up",
"texting leads"
],
"automation_category": "lead_intake_autoreply_and_queue",
"tools_owner_likely_has": [
"web form",
"auto-reply SMS",
"shared sheet"
],
"manual_step_that_stays": "owner qualifies and prices",
"hours_week_low": 2.0,
"hours_week_high": 5.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "leads/day in surge x minutes first response; needs leads/day",
"anti_pattern_to_reject": "hire a cousin to text people"
},
{
"id": "FL-027",
"trade": "Roofing",
"stage": "job_to_invoice",
"leak_category": "claim_paperwork",
"leak_pattern": "Insurance claim paperwork and supplements assembled by hand",
"signal_words": [
"insurance",
"adjuster",
"supplement",
"claim paperwork"
],
"automation_category": "claim_packet_template",
"tools_owner_likely_has": [
"photo folder per job",
"document templates",
"PDF merge"
],
"manual_step_that_stays": "owner negotiates with the adjuster",
"hours_week_low": 2.0,
"hours_week_high": 4.0,
"setup_hours_low": 2.0,
"setup_hours_high": 4.0,
"estimate_basis": "insurance jobs/month x hours assembling; needs claims/month",
"anti_pattern_to_reject": "a binder per job"
},
{
"id": "FL-028",
"trade": "Roofing",
"stage": "invoice_to_money",
"leak_category": "milestone_payment",
"leak_pattern": "Final payment waits on the insurance check with no tracking",
"signal_words": [
"waiting on insurance",
"depreciation check",
"final payment"
],
"automation_category": "milestone_payment_tracking",
"tools_owner_likely_has": [
"invoicing software due dates",
"reminder sequence",
"notes field"
],
"manual_step_that_stays": "owner calls the carrier when overdue",
"hours_week_low": 1.0,
"hours_week_high": 2.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "open claims x check-ins x minutes; needs open claims",
"anti_pattern_to_reject": "a spreadsheet the owner remembers to open"
},
{
"id": "FL-029",
"trade": "Landscaping",
"stage": "call_to_job",
"leak_category": "route_building",
"leak_pattern": "Recurring mow routes rebuilt each week by hand",
"signal_words": [
"route",
"mowing schedule",
"every Tuesday",
"reschedule for rain",
"text each",
"their houses",
"every morning i text"
],
"automation_category": "recurring_job_templates_and_route_order",
"tools_owner_likely_has": [
"scheduling software recurring jobs",
"map app route"
],
"manual_step_that_stays": "crew lead adjusts for weather",
"hours_week_low": 1.0,
"hours_week_high": 3.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "crews x weekly route-build minutes; needs crew count",
"anti_pattern_to_reject": "print the route and mark it up"
},
{
"id": "FL-030",
"trade": "Landscaping",
"stage": "invoice_to_money",
"leak_category": "recurring_billing",
"leak_pattern": "Monthly maintenance customers billed individually and chased",
"signal_words": [
"monthly customers",
"bill everyone",
"who hasn't paid"
],
"automation_category": "recurring_billing_with_autopay",
"tools_owner_likely_has": [
"invoicing software recurring invoices",
"card on file",
"pay link"
],
"manual_step_that_stays": "owner approves new customers",
"hours_week_low": 2.0,
"hours_week_high": 4.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "recurring customers x minutes per invoice + chase; needs customer count",
"anti_pattern_to_reject": "send invoices in one big evening"
},
{
"id": "FL-031",
"trade": "Landscaping",
"stage": "job_to_invoice",
"leak_category": "timesheet_to_payroll",
"leak_pattern": "Crew hours written on a paper sheet and keyed into payroll",
"signal_words": [
"time sheet",
"crew hours",
"payroll Friday"
],
"automation_category": "mobile_clock_in_to_payroll",
"tools_owner_likely_has": [
"phone time-clock app",
"payroll import"
],
"manual_step_that_stays": "owner approves hours",
"hours_week_low": 1.0,
"hours_week_high": 3.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "crew size x days x minutes keying + disputes; needs crew size",
"anti_pattern_to_reject": "text hours to the owner"
},
{
"id": "FL-032",
"trade": "Solar",
"stage": "call_to_job",
"leak_category": "survey_capture",
"leak_pattern": "Site-survey photos and roof measurements sent as loose texts",
"signal_words": [
"survey photos",
"roof measurements",
"send me the pics"
],
"automation_category": "survey_form_with_photo_fields",
"tools_owner_likely_has": [
"phone form with photo upload",
"shared folder per lead"
],
"manual_step_that_stays": "surveyor measures",
"hours_week_low": 1.0,
"hours_week_high": 2.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "surveys/week x minutes collecting + resending; needs surveys/week",
"anti_pattern_to_reject": "a group text per job"
},
{
"id": "FL-033",
"trade": "Solar",
"stage": "job_to_invoice",
"leak_category": "paperwork_prefill",
"leak_pattern": "Utility interconnection and permit paperwork re-typed from the proposal",
"signal_words": [
"interconnection",
"utility application",
"permit packet"
],
"automation_category": "proposal_to_forms_prefill",
"tools_owner_likely_has": [
"proposal PDF export",
"form fill",
"document templates"
],
"manual_step_that_stays": "owner signs and submits",
"hours_week_low": 2.0,
"hours_week_high": 4.0,
"setup_hours_low": 2.0,
"setup_hours_high": 4.0,
"estimate_basis": "installs/month x hours re-typing; needs installs/month",
"anti_pattern_to_reject": "hire an admin for the paperwork"
},
{
"id": "FL-034",
"trade": "Pest",
"stage": "call_to_job",
"leak_category": "renewal_recurring",
"leak_pattern": "Quarterly service customers scheduled by calling each one",
"signal_words": [
"quarterly",
"call to schedule",
"recurring service"
],
"automation_category": "recurring_schedule_with_sms_confirm",
"tools_owner_likely_has": [
"scheduling software recurring jobs",
"SMS confirm"
],
"manual_step_that_stays": "tech does the service",
"hours_week_low": 1.0,
"hours_week_high": 3.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "accounts x 4/year x minutes scheduling; needs account count",
"anti_pattern_to_reject": "a call list every quarter"
},
{
"id": "FL-035",
"trade": "Window_Door",
"stage": "job_to_invoice",
"leak_category": "paperwork_prefill",
"leak_pattern": "Measurement sheets re-typed into the manufacturer order",
"signal_words": [
"measure sheet",
"order form",
"wrong size"
],
"automation_category": "measure_form_feeding_order",
"tools_owner_likely_has": [
"digital measure form",
"order template",
"PDF fill"
],
"manual_step_that_stays": "installer measures",
"hours_week_low": 1.0,
"hours_week_high": 2.0,
"setup_hours_low": 1.0,
"setup_hours_high": 2.0,
"estimate_basis": "orders/month x minutes + remakes; needs orders/month",
"anti_pattern_to_reject": "double-check by hand"
},
{
"id": "FL-036",
"trade": "all",
"stage": "call_to_job",
"leak_category": "eta_communication",
"leak_pattern": "Customer asks the same question repeatedly (are you coming, what time) by phone",
"signal_words": [
"what time are you coming",
"on my way",
"eta calls"
],
"automation_category": "on_my_way_sms",
"tools_owner_likely_has": [
"scheduling software notifications",
"texting app template"
],
"manual_step_that_stays": "tech taps one button",
"hours_week_low": 0.5,
"hours_week_high": 1.0,
"setup_hours_low": 0.5,
"setup_hours_high": 1.0,
"estimate_basis": "jobs/day x eta calls x minutes; needs jobs/day",
"anti_pattern_to_reject": "tell customers a 4-hour window and hope"
}
];
