// GENERATED by tools/gen_engine_assets.py from the QUESTIONS block in assess.html. Do not edit.
export const QUESTIONS = [
{
"stage": "Visibility",
"text": "When did you last know, hour by hour, where a workday actually went?",
"options": [
{
"label": "Never, I couldn't tell you",
"score": 0
},
{
"label": "A few months ago, roughly",
"score": 1
},
{
"label": "This week, I actually tracked it",
"score": 2
}
]
},
{
"stage": "Visibility",
"text": "If someone asked how many hours you personally spent on paperwork or admin last week, could you give a real number?",
"options": [
{
"label": "No idea",
"score": 0
},
{
"label": "A rough guess",
"score": 1
},
{
"label": "Yes, I know the number",
"score": 2
}
]
},
{
"stage": "Visibility",
"text": "Do you know which single task ate the most of your time last week?",
"options": [
{
"label": "No",
"score": 0
},
{
"label": "Sort of",
"score": 1
},
{
"label": "Yes, exactly",
"score": 2
}
]
},
{
"stage": "Leakage",
"text": "How often do you type the same customer info into more than one place (quote, invoice, calendar, texts)?",
"options": [
{
"label": "Every job",
"score": 0
},
{
"label": "Sometimes",
"score": 1
},
{
"label": "Rarely, it's already synced",
"score": 2
}
]
},
{
"stage": "Leakage",
"text": "In the last month, how often did you have to redo or fix something because of a scheduling or paperwork mistake?",
"options": [
{
"label": "Weekly or more",
"score": 0
},
{
"label": "A couple of times",
"score": 1
},
{
"label": "Never",
"score": 2
}
]
},
{
"stage": "Leakage",
"text": "How often do you have to chase someone (a customer, supplier, or employee) for a reply or payment that should show up on its own?",
"options": [
{
"label": "Almost every day",
"score": 0
},
{
"label": "A few times a week",
"score": 1
},
{
"label": "Rarely",
"score": 2
}
]
},
{
"stage": "Leverage",
"text": "Do you already use scheduling or booking software, not just a paper calendar or texts?",
"options": [
{
"label": "No",
"score": 0
},
{
"label": "Yes, but I barely use it",
"score": 1
},
{
"label": "Yes, it runs most of my bookings",
"score": 2
}
]
},
{
"stage": "Leverage",
"text": "A customer texts you at 9pm asking for a quote. What actually happens?",
"options": [
{
"label": "I answer manually whenever I see it",
"score": 0
},
{
"label": "I have a canned reply I copy-paste",
"score": 1
},
{
"label": "It's mostly handled automatically",
"score": 2
}
]
},
{
"stage": "Leverage",
"text": "Have you ever connected two of your business tools together (Zapier, Make, or a built-in automation) so one triggers the other?",
"options": [
{
"label": "Never, not sure how",
"score": 0
},
{
"label": "Tried once, gave up",
"score": 1
},
{
"label": "Yes, I have something running",
"score": 2
}
]
}
];
