// GENERATED by tools/gen_engine_assets.py from kynetica-marketing/engine/tools-catalog.csv. Do not edit.
export const TOOLS = [
{
"tool_id": "T-JOBBER",
"name": "Jobber",
"category": "field_service_platform",
"monthly_low_usd": 39.0,
"monthly_high_usd": 199.0,
"pricing_note": "Core $39 (1 user) to Grow $199 (10 users); card processing 2.9% + 30c",
"best_for": "1 to 15 person trades shops moving off paper; QuickBooks Online sync included on Connect+",
"why_this_one": "Cheapest full platform with job form, price book, invoice-on-completion, reminders, on-my-way texts, review requests and QuickBooks Online sync in one login; the standard first move off paper"
},
{
"tool_id": "T-HCP",
"name": "Housecall Pro",
"category": "field_service_platform",
"monthly_low_usd": 59.0,
"monthly_high_usd": 299.0,
"pricing_note": "Basic $59 (1 user) / Essentials $149 (5 users) / MAX $299 (8 users), annual; monthly billing higher",
"best_for": "3 to 8 tech shops that want consumer-style booking and card payments in the app",
"why_this_one": "Strongest online booking widget and customer texting of the three; QuickBooks sync; price book with parts on the job form"
},
{
"tool_id": "T-ST",
"name": "ServiceTitan",
"category": "field_service_platform",
"monthly_low_usd": 250.0,
"monthly_high_usd": 498.0,
"pricing_note": "Per technician per month, Starter ~$250 to Enterprise ~$498; onboarding fees; annual contract",
"best_for": "10+ techs, call-center dispatch, maintenance agreements at scale",
"why_this_one": "Deepest dispatch, pricebook and call-booking tooling; too heavy and too expensive under ~10 techs"
},
{
"tool_id": "T-QBO",
"name": "QuickBooks Online",
"category": "accounting",
"monthly_low_usd": 38.0,
"monthly_high_usd": 275.0,
"pricing_note": "Simple Start $38 / Essentials $85 / Plus $140 / Advanced $275 (list, before promos)",
"best_for": "The back office almost every trades shop already pays for",
"why_this_one": "Already owned in most shops; mobile app creates invoices on site; automatic invoice reminders, pay links and customer statements are settings inside the owner's login, no API needed"
},
{
"tool_id": "T-SQI",
"name": "Square Invoices",
"category": "invoicing",
"monthly_low_usd": 0.0,
"monthly_high_usd": 20.0,
"pricing_note": "Free plan unlimited invoices; Plus ~$20; card 2.9% + 30c (3.3% + 30c on invoices online)",
"best_for": "Solo or 2 to 3 person shops not on QuickBooks who need invoice-from-the-phone today",
"why_this_one": "Free, five-minute setup, invoice and payment link from the truck; automatic reminders on the free tier"
},
{
"tool_id": "T-QUO",
"name": "Quo (formerly OpenPhone)",
"category": "business_phone_sms",
"monthly_low_usd": 15.0,
"monthly_high_usd": 35.0,
"pricing_note": "$15 / $23 / $35 per user per month",
"best_for": "Shops that want one business number with texting, auto-reply and missed-call text-back without a platform change",
"why_this_one": "Missed-call text-back and after-hours auto-reply are built in; shared number for the office; cheapest route to the most-sold trades automation"
},
{
"tool_id": "T-PODIUM",
"name": "Podium",
"category": "reviews_messaging",
"monthly_low_usd": 249.0,
"monthly_high_usd": 449.0,
"pricing_note": "Quote-based; typically $249 to $449 per month plus AI add-ons",
"best_for": "Larger shops wanting reviews, webchat, texting and payments in one",
"why_this_one": "Strong review generation and missed-call text-back; overkill and overpriced under ~$1M revenue"
},
{
"tool_id": "T-NICEJOB",
"name": "NiceJob",
"category": "reviews",
"monthly_low_usd": 75.0,
"monthly_high_usd": 125.0,
"pricing_note": "Reviews $75; Pro $125",
"best_for": "Shops whose platform lacks a review-request automation",
"why_this_one": "Automatic review requests on job close with follow-ups; integrates with Jobber and Housecall Pro"
},
{
"tool_id": "T-CCAM",
"name": "CompanyCam",
"category": "photo_documentation",
"monthly_low_usd": 79.0,
"monthly_high_usd": 249.0,
"pricing_note": "Core $79 / Crew $149 / Scale $249, seats bundled, extra seat $34",
"best_for": "Roofing, solar, remodel: photo-heavy jobs, insurance and warranty packets",
"why_this_one": "Time-stamped photos per job, shared with office and customer; integrates with Jobber and Housecall Pro; the industry standard for job photos"
},
{
"tool_id": "T-QBT",
"name": "QuickBooks Time",
"category": "time_tracking",
"monthly_low_usd": 20.0,
"monthly_high_usd": 40.0,
"pricing_note": "Premium $20 base + $10 per user; Elite $40 base + $12 per user",
"best_for": "Crews on paper timesheets whose books are in QuickBooks",
"why_this_one": "Mobile clock-in with GPS, approvals, straight into QuickBooks payroll; removes the Friday re-keying"
},
{
"tool_id": "T-GWS",
"name": "Google Workspace (Sheets, Forms, Calendar, Drive)",
"category": "office_suite",
"monthly_low_usd": 7.0,
"monthly_high_usd": 14.0,
"pricing_note": "Business Starter $7 / Standard $14 per user",
"best_for": "Any shop as the free-ish glue: intake forms, shared job sheet, shared calendar, photo folders",
"why_this_one": "Most owners already have Gmail; Forms + Sheets give a mobile job form with photo upload for the cost of a login; Calendar handles shared scheduling with invites"
},
{
"tool_id": "T-STRIPE",
"name": "Stripe (or the platform built-in payments)",
"category": "payments",
"monthly_low_usd": 0.0,
"monthly_high_usd": 0.0,
"pricing_note": "2.9% + 30c per card transaction, no monthly fee",
"best_for": "Pay links in reminders and deposits when the invoicing tool lacks them",
"why_this_one": "No monthly fee; payment links in minutes; the shop's platform (Jobber Payments, HCP Payments, QuickBooks Payments) is usually the simpler choice if they already use it"
},
{
"tool_id": "T-PDFFILL",
"name": "Kynetica PDF prefill (small build)",
"category": "custom_build",
"monthly_low_usd": 0.0,
"monthly_high_usd": 0.0,
"pricing_note": "One-time build $600 to $1,200; hosted on Kynetica's Vercel",
"best_for": "Rebate, warranty, permit, interconnection and claim packets re-typed from job data",
"why_this_one": "A form (or the platform's job export) fills the vendor's PDF; no monthly fee; Kynetica builds and hosts it"
}
];
